use_cuda: True
seed: 2032


InterfacePredictor:
    dataset:
        data_root: ./../pinder/pinder/2024-02/pdbs

        train: datasets/filtered_pinder_train.csv
        val: datasets/filtered_pinder_val.csv
        test: datasets/filtered_pinder_test.csv

        embedding: Rostlab/prot_bert
        distance_threshold: 8

        balance_sample: True
        negative_by_positive: 1  # number negative / number positive
        nsample: 64

    model:
        task: classification
        classification_threshold: 0.5
        input_features: 1024
        hidden_dim: 32
        checkpoint: checkpoints/InterfacePredictor.ckpt

    trainer:
        strategy: ddp_spawn
        accelerator: gpu
        batch_size: 4
        lr: 0.001
        lr_gamma: 0.9
        loss_alpha: 0.9
        loss_gamma: 5
        devices: 1
        max_epochs: 20
        loader_workers: 8
        test_workers: 4
        check_val_every_n_epoch: 1
        accumulate_grad_batches: 2

InteractionPredictor:
    dataset:
        data_root: ./../pinder/pinder/2024-02/pdbs

        train: datasets/train.csv
        val: datasets/val.csv
        test: datasets/test.csv

        embedding: Rostlab/prot_bert
        distance_threshold: 8

    model:
        input_features: 1024
        hidden_dim: 128
        checkpoint: checkpoints/InteractionPredictor.ckpt

    trainer:
        strategy: ddp_spawn
        accelerator: gpu
        batch_size: 16
        lr: 0.001
        lr_gamma: 0.9
        devices: 1
        max_epochs: 20
        loader_workers: 32
        test_workers: 16
        check_val_every_n_epoch: 1
        accumulate_grad_batches: 1
