use_cuda: True
seed: 2032

basic:
    # Embedding of the sequence
    # Option: 'Rostlab/prot_bert', 'Rostlab/prot_t5_xl_uniref50', 'esm2_t33_650M_UR50D', 'onehot'
    embedding: Rostlab/prot_t5_xl_uniref50

    # Device of embedder
    embedder_device: cpu

    # Distance threshold of residue contact
    distance_threshold: 8


dataset:
    train: 
        # Path to pdbs
        data_root: /mnt/f/Research2_pj/pinder/pinder/2024-02/pdbs
        # Path to datasets
        path: datasets/train.csv
        # Type of dataset, option: 
        # - 'ondisk': torch_geometric OnDiskDataset, with pre-calculated sequence embedding
        # - 'csv': csv type dataset with names of pdbs
        # - 'csv_esmac': csv type dataset with sequence, using esm attention contact to build protein graph representation
        type: csv
    val:
        # Path to pdbs
        data_root: /mnt/f/Research2_pj/pinder/pinder/2024-02/pdbs
        # Path to datasets
        path: datasets/val.csv
        # Type of dataset, option: 
        # - 'ondisk': torch_geometric OnDiskDataset, with pre-calculated sequence embedding
        # - 'csv': csv type dataset with names of pdbs
        # - 'csv_esmac': csv type dataset with sequence, using esm attention contact to build protein graph representation
        type: csv
    test:
        # Path to pdbs
        data_root: /mnt/f/Research2_pj/dataset/benchmark_n/all_pdbs
        # Path to datasets
        path: datasets/benchmark.csv
        # Type of dataset, option: 
        # - 'ondisk': torch_geometric OnDiskDataset, with pre-calculated sequence embedding
        # - 'csv': csv type dataset with names of pdbs
        # - 'csv_esmac': csv type dataset with sequence, using esm attention contact to build protein graph representation
        type: csv


trainer:
    strategy: ddp_spawn
    accelerator: gpu
    batch_size: 8
    lr: 0.0001
    devices: 1
    max_epochs: 10
    loader_workers: 32
    test_workers: 16
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 4
